name = "easycode-main-ui"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "easycode-main-ui"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "easycode-cache"

[vars]
NODE_ENV = "production"
NEXTJS_ENV = "production"
NEXT_PUBLIC_APP_NAME = "EasyCode Platform"
NEXT_PUBLIC_APP_VERSION = "1.0.0"
NEXT_PUBLIC_MANTINE_COLOR_SCHEME = "light"
NEXT_PUBLIC_MANTINE_PRIMARY_COLOR = "blue"
NEXT_PUBLIC_ENABLE_TENANT_SWITCHING = "true"
NEXT_PUBLIC_ENABLE_MULTI_TENANCY = "true"
NEXT_PUBLIC_DEFAULT_TENANT_ID = "default"
NEXT_PUBLIC_TENANT_DOMAIN_SUFFIX = ".easycode.com" 