[build]
  base = "apps/main-ui"
  publish = "out"
  command = "cp package.netlify.json package.json && cp next.config.netlify.js next.config.js && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY = "true"

# Force pnpm usage
[build.processing]
  skip_processing = false

[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Finance module routes
[[redirects]]
  from = "/finance/*"
  to = "/finance/index.html"
  status = 200

# Dashboard and other app routes
[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/crm/*"
  to = "/crm/index.html"
  status = 200

[[redirects]]
  from = "/projects/*"
  to = "/projects/index.html"
  status = 200

# API routes (if any)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 